### ISSUE TITLE
ScrollController doesn't want center justified display objects

### ISSUE THREAD

**Issue by EddieOne** [freshplanet/Air-Mobile-ScrollController#3]
The class will act strange if the display object is Not justified to the top left. Also, not using the contentRect variable caused some strange bouncing behavior and a hidden scrollbar. It might be the same justification problem.

**Comment by manfye** [comment]
can u teach me how to use the scrollbar @_@" the instruction is not so clear

**Comment by EddieOne** [comment]
1. Create a new Actionscript 3.0 file in flash IDE.
2. Save the new .fla file in the same folder as ScrollController.as
3. create a textbox, fill it with random text, change the instance name to scrollTxt.

4.put the following code on frame 1:

import flash.geom.Rectangle;
import flash.text.TextFieldAutoSize;
import ScrollController;

scrollTxt.autoSize = TextFieldAutoSize.CENTER
scrollTxt.multiline = true;
scrollTxt.wordWrap = true;
var scrollCon = new ScrollController();
var scrollMask = new Rectangle(5, 16, 390, 110);
var contentRec = new Rectangle(0, 0, scrollTxt.width, scrollTxt.height);

scrollCon.addScrollControll(this.scrollTxt, stage, scrollMask, contentRec);

**Comment by manfye** [comment]
thanks you very much! appreciated it! :dancer:
